version: '3.8'
x-app: &app
  build:
    context: .
    target: hyku-web
    cache_from:
      - ghcr.io/samvera/hyku/base:latest
      - ghcr.io/notch8/wvu_knapsack:latest
    args:
      BUILDKIT_INLINE_CACHE: 1
      APP_PATH: ./hyrax-webapp
  image: ghcr.io/notch8/wvu_knapsack:${TAG:-latest}
  environment:
    # This line is what makes the knapsack include use the local code instead of the remote gem
    - BUNDLE_LOCAL__HYKU_KNAPSACK=/app/samvera
    - BUNDLE_DISABLE_LOCAL_BRANCH_CHECK=true
    - BUNDLE_BUNDLER_INJECT__GEM_PATH=/app/samvera/bundler.d
  volumes:
    - node_modules:/app/samvera/hyrax-webapp/node_modules:cached
    - uploads:/app/samvera/hyrax-webapp/public/uploads:cached
    - assets:/app/samvera/hyrax-webapp/public/assets:cached
    - cache:/app/samvera/hyrax-webapp/tmp/cache:cached
    - .:/app/samvera

volumes:
  assets:
  cache:
  db:
  fcrepo:
  node_modules:
  redis:
  solr:
  uploads:
  zk:
  zoo:

networks:
  internal:

services:
  zoo:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: zoo

  solr:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: solr

  fcrepo:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: fcrepo

  db:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: db

  base:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: base
    image: ghcr.io/samvera/hyku/base:${TAG:-latest}
    command: bash -l -c "echo 'base is only used for building base images, which in turn reduces image build times. It does not need to be run'"

  web:
    <<: *app
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: web
    # Uncomment command to access container with out starting bin/web. Useful for debugging or updating Gemfile.lock
    # command: sleep infinity
    environment:
      # This line is what makes the knapsack include use the local code instead of the remote gem
      - BUNDLE_LOCAL__HYKU_KNAPSACK=/app/samvera
      - BUNDLE_DISABLE_LOCAL_BRANCH_CHECK=true
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=.hyku.test

  worker:
    <<: *app
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: worker
    build:
      context: .
      target: hyku-worker
      cache_from:
        - ghcr.io/samvera/hyku/base:latest
        - ghcr.io/samvera-labs/hyku_knapsack/worker:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
        APP_PATH: ./hyrax-webapp
    image: ghcr.io/notch8/wvu_knapsack/worker:${TAG:-latest}
    # Uncomment command to access container with out starting bin/worker. Useful for debugging or updating Gemfile.lock
    # command: sleep infinity
    volumes:
      - node_modules:/app/samvera/hyrax-webapp/node_modules:cached
      - uploads:/app/samvera/hyrax-webapp/public/uploads:cached
      - assets:/app/samvera/hyrax-webapp/public/assets:cached
      - cache:/app/samvera/hyrax-webapp/tmp/cache:cached
      - .:/app/samvera

  check_volumes:
    <<: *app
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: check_volumes

  initialize_app:
    <<: *app
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: initialize_app

  redis:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: redis

  chrome:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: chrome
