x-app: &app
  env_file:
    - .env.production
  build:
    context: .
    target: hyku-web
    cache_from:
      - ghcr.io/samvera/hyku/base:latest
      - ghcr.io/samvera-labs/hyku_knapsack:latest
    args:
      BUILDKIT_INLINE_CACHE: 1
      APP_PATH: ./hyrax-webapp
  image: ghcr.io/notch8/wvu_knapsack:${TAG:-latest}
  environment:
    # This line is what makes the knapsack include use the local code instead of the remote gem
    - BUNDLE_LOCAL__HYKU_KNAPSACK=/app/samvera
    - BUNDLE_DISABLE_LOCAL_BRANCH_CHECK=true
    - BUNDLE_BUNDLER_INJECT__GEM_PATH=/app/samvera/bundler.d
  volumes:
    - node_modules:/app/samvera/hyrax-webapp/node_modules:cached
    - uploads:/app/samvera/hyrax-webapp/public/uploads:cached
    - assets:/app/samvera/hyrax-webapp/public/assets:cached
    - cache:/app/samvera/hyrax-webapp/tmp/cache:cached
    - .:/app/samvera

volumes:
  assets:
  cache:
  db:
  fcrepo:
  node_modules:
  redis:
  solr:
  uploads:
  zk:
  zoo:

networks:
  internal:

services:
  zoo:
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: zoo

  solr:
    build:
      context: .
      target: hyku-solr
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - ghcr.io/samvera/hyku/solr:latest
    image: ghcr.io/samvera/hyku/solr:${TAG:-latest}
    environment:
      - OOM=script
      - SOLR_ADMIN_USER=solr
      - SOLR_ADMIN_PASSWORD=SolrRocks
      - SOLR_COLLECTION=hydra-development
      - SOLR_CLOUD_BOOTSTRAP=yes
      - SOLR_ENABLE_CLOUD_MODE=yes
      - SOLR_ENABLE_AUTHENTICATION=yes
      - ZK_HOST=zoo:2181
      - VIRTUAL_PORT=8983
      - VIRTUAL_HOST=solr.hyku.test
    user: root
    command: bash -c "
      chown -R 8983:8983 /var/solr
      && ./bin/solr zk cp file:/var/solr/data/security.json zk:/security.json
      && runuser -u solr -- solr-foreground"
    expose:
      - 8983
    volumes:
      - solr:/var/solr
    networks:
      internal:
    healthcheck:
      test: curl -sf http://$$SOLR_ADMIN_USER:$$SOLR_ADMIN_PASSWORD@solr:8983/solr/admin/cores?action=STATUS || exit 1
      start_period: 3s
      interval: 5s
      timeout: 5s
      retries: 6
    depends_on:
      zoo:
        condition: service_healthy

  fcrepo:
    env_file:
      - .env.production
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: fcrepo

  db:
    env_file:
      - .env.production
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: db

  web:
    <<: *app
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: web
    # Uncomment command to access container with out starting bin/web. Useful for debugging or updating Gemfile.lock
    # command: sleep infinity
    environment:
      # This line is what makes the knapsack include use the local code instead of the remote gem
      - BUNDLE_LOCAL__HYKU_KNAPSACK=/app/samvera
      - BUNDLE_DISABLE_LOCAL_BRANCH_CHECK=true
      - VIRTUAL_PORT=3000
    ports:
      - "3000:3000"

  worker:
    <<: *app
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: worker
    build:
      context: .
      target: hyku-worker
      cache_from:
        - ghcr.io/samvera/hyku/base:latest
        - ghcr.io/notch8/wvu_knapsack/worker:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
        APP_PATH: ./hyrax-webapp
    image: ghcr.io/notch8/wvu_knapsack/worker:${TAG:-latest}
    # Uncomment command to access container with out starting bin/worker. Useful for debugging or updating Gemfile.lock
    # command: sleep infinity
    volumes:
      - node_modules:/app/samvera/hyrax-webapp/node_modules:cached
      - uploads:/app/samvera/hyrax-webapp/public/uploads:cached
      - assets:/app/samvera/hyrax-webapp/public/assets:cached
      - cache:/app/samvera/hyrax-webapp/tmp/cache:cached
      - .:/app/samvera

  check_volumes:
    <<: *app
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: check_volumes

  initialize_app:
    <<: *app
    command:
      - >
        solrcloud-upload-configset.sh /app/samvera/hyrax-webapp/solr/conf &&
        solrcloud-assign-configset.sh &&
        SOLR_COLLECTION_NAME=hydra-test solrcloud-assign-configset.sh &&
        db-migrate-seed.sh
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: initialize_app

  redis:
    extends:
      file: hyrax-webapp/docker-compose.production.yml
      service: redis
