# playbook.yml
---
- name: Basic tasks
  # This host is defined in the `inventory.yml`
  hosts: production
  tasks:
    - name: Execute uptime command
      command: uptime
      register: uptime_result
    - debug: var=uptime_result.stdout_lines
    - name: Check RHEL OS release
      command: cat /etc/redhat-release
      register: os_result
      when: ansible_facts['os_family'] == 'RedHat'
    - debug: var=os_result.stdout_lines

# ansible-playbook -i ./ansible/inventory.ini ./ansible/playbook.yml
