# playbook.yml
# ---
# - name: Basic tasks
#   # This host is defined in the `inventory.yml`
#   hosts: production
#   tasks:
#     - name: Execute uptime command
#       command: uptime
#       register: uptime_result
#     - debug: var=uptime_result.stdout_lines
#     - name: Check RHEL OS release
#       command: cat /etc/redhat-release
#       register: os_result
#       when: ansible_facts['os_family'] == 'RedHat'
#     - debug: var=os_result.stdout_lines
---
- name: Setup WVU Server
  hosts: localhost
  connection: local
  become: true
  vars:
    root_group: root

  roles:
    - role: base_setup
      tags: base
    - role: nginx-badbot-blocker
      tags: nginx

  tasks:

    - name: Copy SSL certificate
      copy:
        src: files/hykudev_lib_wvu_edu_2024_complete.cer
        dest: /etc/ssl/hykudev_lib_wvu_edu_2024_complete.cer
        mode: '0644'

    - name: Copy SSL key
      copy:
        src: files/hykudev.lib.wvu.edu.2024.key
        dest: /etc/ssl/private/hykudev.lib.wvu.edu.2024.key
        mode: '0600'

    - name: Copy nginx configuration
      copy:
        src: files/nginx-default
        dest: /etc/nginx/sites-enabled/default
        mode: '0644'
      notify: restart nginx

    # - name: Create user accounts
    #   user:
    #     name: "{{ item.name }}"
    #     state: present
    #     create_home: yes
    #     groups: adm,sudo,docker
    #   with_items:
    #     "{{ ssh_users }}"

    # - name: Configure sudo without password
    #   copy:
    #     dest: "/etc/sudoers.d/{{ item.name }}"
    #     content: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
    #     mode: '0440'
    #     validate: /usr/sbin/visudo -cf %s
    #   with_items:
    #     "{{ ssh_users }}"

    # - name: set up github keys
    #   authorized_key:
    #     user: "{{ item.name }}"
    #     state: present
    #     key: "https://github.com/{{ item.github }}.keys"
    #   with_items:
    #     "{{ ssh_users }}"

    # - name: Configure Docker login
    #   docker_login:
    #     registry_url: ghcr.io
    #     username: orangewolf
    #     password: "{{ ghcr_token }}"

    # - name: Copy deploy key
    #   copy:
    #     src: files/id_rsa
    #     dest: /root/.ssh/id_rsa
    #     mode: '0600'
    #     owner: root
    #     group: root

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

# ansible-playbook -i ./ansible/inventory.ini ./ansible/playbook.yml
