name: "Build Solr"
run-name: Build Solr of ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      debug_step:
        required: false
        description: 'Pause the selected step to debug using tmate'
        type: choice
        default: ""
        options:
          - ""
          - build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Downcase repo
        run: echo "REPO_LOWER=${REPO,,}" >> $GITHUB_ENV
        env:
          REPO: '${{ github.repository }}'
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Github Container Login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./hyrax-webapp
          platforms: linux/amd64,linux/arm64
          target: hyku-solr
          push: true
          tags: |
            ghcr.io/wvulibraries/wvu_knapsack/solr:${{ env.TAG }}
            ghcr.io/wvulibraries/wvu_knapsack/solr:latest